In [1]:
import pandas as pd
Data={
    "Marks":[95,67,89,76,65,53,39,83,65,75],
    "Sleep Hours":[7,6,7,7,7,6,5,7,6,7],
    "Sample Question Papers Practised":[5,4,4,5,4,4,3,5,4,5],
    "Sample Papers Average Marks":[90,65,84,70,62,49,40,77,63,74]
}
df=pd.DataFrame(Data)
df.to_csv("Student_Performance.csv")
print(df)

   Marks  Sleep Hours  Sample Question Papers Practised  \
0     95            7                                 5
1     67            6                                 4
2     89            7                                 4
3     76            7                                 5
4     65            7                                 4
5     53            6                                 4
6     39            5                                 3
7     83            7                                 5
8     65            6                                 4
9     75            7                                 5

   Sample Papers Average Marks
0                           90
1                           65
2                           84
3                           70
4                           62
5                           49
6                           40
7                           77
8                           63
9                           74

In [2]:
df.mode()

,Marks,Sleep Hours,Sample Question Papers Practised,Sample Papers Average Marks
0,65.0,7.0,4.0,40
1,NaN,NaN,NaN,49
2,NaN,NaN,NaN,62
3,NaN,NaN,NaN,63
4,NaN,NaN,NaN,65
5,NaN,NaN,NaN,70
6,NaN,NaN,NaN,74
7,NaN,NaN,NaN,77
8,NaN,NaN,NaN,84
9,NaN,NaN,NaN,90

In [3]:
df.std()

Marks                               16.733533
Sleep Hours                          0.707107
Sample Question Papers Practised     0.674949
Sample Papers Average Marks         15.174540
dtype: float64

In [4]:
df["Marks"].sum()

np.int64(707)

In [5]:
df.describe()

,Marks,Sleep Hours,Sample Question Papers Practised,Sample Papers Average Marks
count,10.000000,10.000000,10.000000,10.00000
mean,70.700000,6.500000,4.300000,67.40000
std,16.733533,0.707107,0.674949,15.17454
min,39.000000,5.000000,3.000000,40.00000
25%,65.000000,6.000000,4.000000,62.25000
50%,71.000000,7.000000,4.000000,67.50000
75%,81.250000,7.000000,5.000000,76.25000
max,95.000000,7.000000,5.000000,90.00000

In [6]:
df["Marks"].std()

np.float64(16.733532535334884)

In [7]:
import pandas as pd
df=pd.read_csv("Student_Performance.csv")
data3=df.drop(columns=["Sample Question Papers Practised","Sample Papers Average Marks"],inplace=False,axis=1)
data3.head()

ValueError: Cannot specify both 'axis' and 'index'/'columns'