In [6]:
import pandas as pd
data={
    "Marks":[76,59,90,31,67,89,90,66,77,57],
    "Co-carricular Activities":["Yes","Yes","No","NO","Yes","No","Yes","No","Yes","Yes"],
    "Sample Papers done":[4,4,3,None,4,5,5,3,4,2],
    "Sample Papers' Average":[78,54,87,None,63,83,82,60,78,55]
}
df=pd.DataFrame(data)
print(df)
df.to_csv("Student_Perfomance.csv")

   Marks Co-carricular Activities  Sample Papers done  Sample Papers' Average
0     76                      Yes                 4.0                    78.0
1     59                      Yes                 4.0                    54.0
2     90                       No                 3.0                    87.0
3     31                       NO                 NaN                     NaN
4     67                      Yes                 4.0                    63.0
5     89                       No                 5.0                    83.0
6     90                      Yes                 5.0                    82.0
7     66                       No                 3.0                    60.0
8     77                      Yes                 4.0                    78.0
9     57                      Yes                 2.0                    55.0

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Marks                     10 non-null     int64
 1   Co-carricular Activities  10 non-null     str
 2   Sample Papers done        9 non-null      float64
 3   Sample Papers' Average    9 non-null      float64
dtypes: float64(2), int64(1), str(1)
memory usage: 452.0 bytes

In [11]:
df.columns

Index(['Marks', 'Co-carricular Activities', 'Sample Papers done',
       'Sample Papers' Average'],
      dtype='str')

In [12]:
df.shape

(10, 4)

In [16]:

df.isnull()

,Unnamed: 0,Marks,Co-carricular Activities,Sample Papers done,Sample Papers' Average
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,True,True
4,False,False,False,False,False
5,False,False,False,False,False
6,False,False,False,False,False
7,False,False,False,False,False
8,False,False,False,False,False
9,False,False,False,False,False

In [17]:
df.describe()

       Unnamed: 0      Marks  Sample Papers done  Sample Papers' Average
count    10.00000  10.000000            9.000000                9.000000
mean      4.50000  70.200000            3.777778               71.111111
std       3.02765  18.504054            0.971825               12.985034
min       0.00000  31.000000            2.000000               54.000000
25%       2.25000  60.750000            3.000000               60.000000
50%       4.50000  71.500000            4.000000               78.000000
75%       6.75000  86.000000            4.000000               82.000000
max       9.00000  90.000000            5.000000               87.000000